/* eslint-disable @typescript-eslint/no-explicit-any */
export const phoneNumberValidations: Record<
  string,
  (number: string) => boolean
> = {
  "+93": (number: any) => /^\d{9}$/.test(number), // Afghanistan: 9 digits
  "+358": (number: any) => /^\d{9,10}$/.test(number), // Åland Islands: 9 or 10 digits
  "+355": (number: any) => /^\d{8}$/.test(number), // Albania: 8 digits
  "+213": (number: any) => /^\d{9}$/.test(number), // Algeria: 9 digits
  "+376": (number: any) => /^\d{6}$/.test(number), // Andorra: 6 digits
  "+244": (number: any) => /^\d{9}$/.test(number), // Angola: 9 digits
  "+374": (number: any) => /^\d{8}$/.test(number), // Armenia: 8 digits
  "+297": (number: any) => /^\d{7}$/.test(number), // Aruba: 7 digits
  "+247": (number: any) => /^\d{4}$/.test(number), // Ascension Island: 4 digits
  "+43": (number: any) => /^\d{10}$/.test(number), // Austria: 10 digits
  "+994": (number: any) => /^\d{9}$/.test(number), // Azerbaijan: 9 digits
  "+880": (number: any) => /^\d{10}$/.test(number), // Bangladesh: 10 digits
  "+375": (number: any) => /^\d{9,10}$/.test(number), // Belarus: 9 or 10 digits
  "+32": (number: any) => /^\d{9}$/.test(number), // Belgium: 9 digits
  "+501": (number: any) => /^\d{7}$/.test(number), // Belize: 7 digits
  "+229": (number: any) => /^\d{8}$/.test(number), // Benin: 8 digits
  "+975": (number: any) => /^\d{8}$/.test(number), // Bhutan: 8 digits
  "+591": (number: any) => /^\d{8}$/.test(number), // Bolivia: 8 digits
  "+599": (number: any) => /^\d{7}$/.test(number), // Curaçao: 7 digits
  "+387": (number: any) => /^\d{8}$/.test(number), // Bosnia and Herzegovina: 8 digits
  "+267": (number: any) => /^\d{8}$/.test(number), // Lesotho: 8 digits
  "+246": (number: any) => /^\d{4,5}$/.test(number), // Saint Helena, Ascension and Tristan da Cunha: 4 to 5 digits
  "+673": (number: any) => /^\d{7}$/.test(number), // Brunei: 7 digits
  "+359": (number: any) => /^\d{8}$/.test(number), // Bulgaria: 8 digits
  "+226": (number: any) => /^\d{8}$/.test(number), // Burkina Faso: 8 digits
  "+257": (number: any) => /^\d{8}$/.test(number), // Burundi: 8 digits
  "+237": (number: any) => /^\d{9}$/.test(number), // Cameroon: 9 digits
  "+238": (number: any) => /^\d{7}$/.test(number), // Cape Verde: 7 digits
  "+236": (number: any) => /^\d{9}$/.test(number), // Cameroon: 9 digits
  "+235": (number: any) => /^\d{8}$/.test(number), // Central African Republic: 8 digits
  "+1": (number: any) => /^\d{10}$/.test(number), // USA: Exactly 10 digits
  "+44": (number: any) => /^7\d{9}$/.test(number), // UK: Typically starts with 7 and has 10 digits
  "+91": (number: any) => /^[6-9]\d{9}$/.test(number), // India: Starts with 6-9 and 10 digits
  "+61": (number: any) => /^\d{9}$/.test(number), // Australia: 9 digits
  "+33": (number: any) => /^0\d{9}$/.test(number), // France: Starts with 0 and has 10 digits
  "+49": (number: any) => /^\d{10,11}$/.test(number), // Germany: 10-11 digits
  "+81": (number: any) => /^\d{10}$/.test(number), // Japan: 10 digits
  "+82": (number: any) => /^\d{10}$/.test(number), // South Korea: 10 digits
  "+55": (number: any) => /^\d{10,11}$/.test(number), // Brazil: 10 or 11 digits
  "+34": (number: any) => /^\d{9}$/.test(number), // Spain: 9 digits
  "+39": (number: any) => /^\d{10}$/.test(number), // Italy: 10 digits
  "+52": (number: any) => /^\d{10}$/.test(number), // Mexico: 10 digits
  "+86": (number: any) => /^\d{11}$/.test(number), // China: 11 digits
  "+7": (number: any) => /^\d{10,11}$/.test(number), // Russia: 10-11 digits
  "+27": (number: any) => /^\d{9,10}$/.test(number), // South Africa: 9 or 10 digits
  "+31": (number: any) => /^\d{9}$/.test(number), // Netherlands: 9 digits
  "+48": (number: any) => /^\d{9}$/.test(number), // Poland: 9 digits
  "+47": (number: any) => /^\d{8}$/.test(number), // Norway: 8 digits
  "+64": (number: any) => /^\d{9}$/.test(number), // New Zealand: 9 digits
  "+20": (number: any) => /^\d{10}$/.test(number), // Egypt: 10 digits
  "+30": (number: any) => /^\d{10}$/.test(number), // Greece: 10 digits
  "+54": (number: any) => /^\d{10}$/.test(number), // Argentina: 10 digits
  "+977": (number: any) => /^\d{10}$/.test(number), // Nepal: 10 digits
  "+45": (number: any) => /^\d{8}$/.test(number), // Denmark: 8 digits
  "+62": (number: any) => /^\d{9,10}$/.test(number), // Indonesia: 9-10 digits
  "+63": (number: any) => /^\d{10}$/.test(number), // Philippines: 10 digits
  "+65": (number: any) => /^\d{8}$/.test(number), // Singapore: 8 digits
  "+971": (number: any) => /^\d{9}$/.test(number), // UAE: 9 digits
  "+420": (number: any) => /^\d{9}$/.test(number), // Czech Republic: 9 digits
  "+60": (number: any) => /^\d{9,10}$/.test(number), // Malaysia: 9-10 digits
  "+66": (number: any) => /^\d{9}$/.test(number), // Thailand: 9 digits
  "+90": (number: any) => /^\d{10}$/.test(number), // Turkey: 10 digits
  "+98": (number: any) => /^\d{10}$/.test(number), // Iran: 10 digits
  "+92": (number: any) => /^\d{10}$/.test(number), // Pakistan: 10 digits
  "+254": (number: any) => /^\d{9}$/.test(number), // Kenya: 9 digits
  "+234": (number: any) => /^\d{10}$/.test(number), // Nigeria: 10 digits
  "+256": (number: any) => /^\d{9}$/.test(number), // Uganda: 9 digits
  "+233": (number: any) => /^\d{10}$/.test(number), // Ghana: 10 digits
  "+973": (number: any) => /^\d{8}$/.test(number), // Bahrain: 8 digits
  "+353": (number: any) => /^\d{9}$/.test(number), // Ireland: 9 digits
  "+380": (number: any) => /^\d{9}$/.test(number), // Ukraine: 9 digits
  "+855": (number: any) => /^\d{9}$/.test(number), // Cambodia: 9 digits
  "+243": (number: any) => /^\d{9}$/.test(number), // DR Congo: 9 digits
  "+266": (number: any) => /^\d{8}$/.test(number), // Lesotho: 8 digits
  "+248": (number: any) => /^\d{4}$/.test(number), // Seychelles: 4 digits
  "+253": (number: any) => /^\d{7}$/.test(number), // Djibouti: 7 digits
  "+250": (number: any) => /^\d{9}$/.test(number), // Rwanda: 9 digits
  "+56": (number: any) => /^\d{9}$/.test(number), // Chile: 9 digits
  "+57": (number: any) => /^\d{10}$/.test(number), // Colombia: 10 digits
  "+269": (number: any) => /^\d{7}$/.test(number), // Comoros: 7 digits
  "+242": (number: any) => /^\d{7}$/.test(number), // Republic of the Congo: 7 digits
  "+682": (number: any) => /^\d{4}$/.test(number), // Cook Islands: 4 digits
  "+506": (number: any) => /^\d{8}$/.test(number), // Costa Rica: 8 digits
  "+225": (number: any) => /^\d{8}$/.test(number), // Ivory Coast: 8 digits
  "+385": (number: any) => /^\d{9}$/.test(number), // Croatia: 9 digits
  "+53": (number: any) => /^\d{8}$/.test(number), // Cuba: 8 digits
  "+94": (number) => /^\d{10}$/.test(number), // Sri Lanka: 10 digits
  "+41": (number) => /^\d{9}$/.test(number), // Switzerland: 9 digits
  "+46": (number) => /^\d{9}$/.test(number), // Sweden: 9 digits
  "+85": (number) => /^\d{10}$/.test(number), // Vietnam: 10 digits
  "+357": (number) => /^\d{9}$/.test(number), // Cyprus: 9 digits
  "+593": (number) => /^\d{9}$/.test(number), // Ecuador: 9 digits
  "+503": (number) => /^\d{8}$/.test(number), // El Salvador: 8 digits
  "+240": (number) => /^\d{7}$/.test(number), // Equatorial Guinea: 7 digits
  "+291": (number) => /^\d{7}$/.test(number), // Eritrea: 7 digits
  "+372": (number) => /^\d{7,9}$/.test(number), // Estonia: 7 to 9 digits
  "+251": (number) => /^\d{9}$/.test(number), // Ethiopia: 9 digits
  "+500": (number) => /^\d{5}$/.test(number), // Falkland Islands: 5 digits
  "+298": (number) => /^\d{6}$/.test(number), // Greenland: 6 digits
  "+691": (number) => /^\d{7}$/.test(number), // Federated States of Micronesia: 7 digits
  "+679": (number) => /^\d{6,7}$/.test(number), // Fiji: 6 or 7 digits
  "+594": (number) => /^0[1-9]\d{7}$/.test(number), // French Guiana: 9 digits, starting with a 0
  "+689": (number) => /^(40|87)\d{6}$/.test(number), // French Polynesia: 8 digits, starting with 40 or 87
  "+241": (number) => /^\d{7}$/.test(number), // Gabon: 7 digits
  "+220": (number) => /^\d{7}$/.test(number), // The Gambia: 7 digits
  "+995": (number) => /^\d{9}$/.test(number), // Georgia: 9 digits
  "+350": (number) => /^(?:\d{8})$/.test(number), // Gibraltar: 8 digits
  "+299": (number) => /^(?:\d{8})$/.test(number), // Greenland: 8 digits
  "+590": (number) => /^(?:\d{9})$/.test(number), // Guadeloupe: 9 digits
  "+502": (number) => /^(?:\d{8})$/.test(number), // Guatemala: 8 digits
  "+224": (number) => /^\d{9}$/.test(number), // Guinea: 9 digits after country code
  "+245": (number) => /^\d{7}$/.test(number), // Guinea-Bissau: 7 digits after country code
  "+592": (number) => /^\d{7}$/.test(number), // Guyana: 7 digits after country code
  "+509": (number) => /^\d{8}$/.test(number), // Haiti: 8 digits after country code
  "+504": (number) => /^\d{8}$/.test(number), // Honduras: 8 digits after country code
  "+852": (number) => /^\d{8}$/.test(number), // Hong Kong: 8 digits after country code
  "+36": (number) => /^\d{9}$/.test(number), // Hungary: 9 digits after country code
  "+354": (number) => /^\d{7}$/.test(number), // Iceland: 7 digits after country code
  "+964": (number) => /^[0-9]{9}$/.test(number), // Iraq: 9 digits after country code
  "+972": (number) => /^[5-9][0-9]{8}$/.test(number), // Israel: 9 digits after country code, starting with 5, 7, 8, or 9
  "+962": (number) => /^[7-9][0-9]{8}$/.test(number), // Jordan: 9 digits after country code, starting with 7, 8, or 9
  "+686": (number) => /^[0-9]{5}$/.test(number), // Kiribati: 5 digits after country code
  "+383": (number) => /^[0-9]{8}$/.test(number), // Kosovo: 8 digits after country code
  "+965": (number) => /^[0-9]{8}$/.test(number), // Kuwait: 8 digits after country code
  "+996": (number) => /^[0-9]{9}$/.test(number), // Kyrgyzstan: 9 digits after country code
  "+856": (number) => /^[0-9]{8,9}$/.test(number), // Laos: 8 or 9 digits after country code
  "+371": (number) => /^[0-9]{8}$/.test(number), // Latvia: 8 digits after country code
  "+961": (number) => /^[0-9]{8}$/.test(number), // Lebanon: 8 digits after country code
  "+231": (number) => /^[0-9]{7}$/.test(number), // Liberia: 7 digits after country code
  "+218": (number) => /^[0-9]{9}$/.test(number), // Libya: 9 digits after country code
  "+423": (number) => /^[0-9]{8}$/.test(number), // Liechtenstein: 8 digits after country code
  "+370": (number) => /^[0-9]{8}$/.test(number), // Lithuania: 8 digits after country code
  "+853": (number) => /^[0-9]{8}$/.test(number), // Macau: 8 digits after country code
  "+352": (number) => /^[0-9]{6,9}$/.test(number), // Luxembourg: 6-9 digits after country code
  "+261": (number) => /^[0-9]{9}$/.test(number), // Madagascar: 9 digits after country code
  "+265": (number) => /^[0-9]{7,9}$/.test(number), // Malawi: 7-9 digits after country code
  "+960": (number) => /^[0-9]{7}$/.test(number), // Maldives: 7 digits after country code
  "+223": (number) => /^[0-9]{8}$/.test(number), // Mali: 8 digits after country code
  "+356": (number) => /^[0-9]{8}$/.test(number), // Malta: 8 digits after country code
  "+692": (number) => /^[0-9]{7}$/.test(number), // Marshall Islands: 7 digits after country code
  "+596": (number) => /^[0-9]{9}$/.test(number), // Martinique: 9 digits after country code
  "+222": (number) => /^[0-9]{8}$/.test(number), // Mauritania: 8 digits after country code
  "+230": (number) => /^[0-9]{7,8}$/.test(number), // Mauritius: 7-8 digits after country code
  "+262": (number) => /^[0-9]{9}$/.test(number), // Mayotte: 9 digits after country code
  "+373": (number) => /^[0-9]{8}$/.test(number), // Moldova: 8 digits after country code
  "+377": (number) => /^[0-9]{8,9}$/.test(number), // Monaco: 8-9 digits after country code
  "+976": (number) => /^[0-9]{8}$/.test(number), // Mongolia: 8 digits after country code
  "+382": (number) => /^[0-9]{8}$/.test(number), // Montenegro: 8 digits after country code
  "+212": (number) => /^[0-9]{9}$/.test(number), // Morocco: 9 digits after country code
  "+258": (number) => /^[0-9]{8,9}$/.test(number), // Mozambique: 8-9 digits after country code
  "+95": (number) => /^[0-9]{7,10}$/.test(number), // Myanmar (Burma): 7-10 digits after country code
  "+264": (number) => /^[0-9]{7,9}$/.test(number), // Namibia: 7-9 digits after country code
  "+674": (number) => /^[0-9]{7}$/.test(number), // Nauru: 7 digits after country code
  "+687": (number) => /^[0-9]{6}$/.test(number), // New Caledonia: 6 digits after country code
  "+505": (number) => /^[0-9]{8}$/.test(number), // Nicaragua: 8 digits after country code
  "+227": (number) => /^[0-9]{8}$/.test(number), // Niger: 8 digits after country code
  "+683": (number) => /^[0-9]{4}$/.test(number), // Niue: 4 digits after country code
  "+672": (number) => /^[0-9]{6}$/.test(number), // Norfolk Island: 6 digits after country code
  "+850": (number) => /^[0-9]{8,10}$/.test(number), // North Korea: 8-10 digits after country code
  "+389": (number) => /^[0-9]{8}$/.test(number), // North Macedonia: 8 digits after country code
  "+968": (number) => /^[0-9]{8}$/.test(number), // Oman: 8 digits after country code
  "+970": (number) => /^[0-9]{9}$/.test(number), // Palestine: 9 digits after country code
  "+507": (number) => /^[0-9]{7,8}$/.test(number), // Panama: 7-8 digits after country code
  "+675": (number) => /^[0-9]{7,8}$/.test(number), // Papua New Guinea: 7-8 digits after country code
  "+595": (number) => /^[0-9]{9}$/.test(number), // Paraguay: 9 digits after country code
  "+51": (number) => /^[0-9]{9}$/.test(number), // Peru: 9 digits after country code
  "+351": (number) => /^[0-9]{9}$/.test(number), // Portugal: 9 digits after country code
  "+974": (number) => /^[0-9]{8}$/.test(number), // Qatar: 8 digits after country code
  "+40": (number) => /^[0-9]{9}$/.test(number), // Romania: 9 digits after country code
  "+290": (number) => /^[0-9]{4}$/.test(number), // Saint Helena: 4 digits after country code
  "+508": (number) => /^[0-9]{6}$/.test(number), // Saint Pierre and Miquelon: 6 digits after country code
  "+685": (number) => /^[0-9]{5,7}$/.test(number), // Samoa: 5-7 digits after country code
  "+378": (number) => /^[0-9]{6,10}$/.test(number), // San Marino: 6-10 digits after country code
  "+239": (number) => /^[0-9]{7}$/.test(number), // São Tomé and Príncipe: 7 digits after country code
  "+966": (number) => /^[0-9]{9}$/.test(number), // Saudi Arabia: 9 digits after country code
  "+221": (number) => /^[0-9]{9}$/.test(number), // Senegal: 9 digits after country code
  "+381": (number) => /^[0-9]{8,9}$/.test(number), // Serbia: 8-9 digits after country code
  "+232": (number) => /^[0-9]{8}$/.test(number), // Sierra Leone: 8 digits after country code
  "+421": (number) => /^[0-9]{9}$/.test(number), // Slovakia: 9 digits after country code
  "+677": (number) => /^[0-9]{5,7}$/.test(number), // Solomon Islands: 5-7 digits after country code
  "+252": (number) => /^[0-9]{8}$/.test(number), // Somalia: 8 digits after country code
  "+211": (number) => /^[0-9]{9}$/.test(number), // South Sudan: 9 digits after country code
  "+249": (number) => /^[0-9]{9}$/.test(number), // Sudan: 9 digits after country code
  "+597": (number) => /^[0-9]{6,7}$/.test(number), // Suriname: 6-7 digits after country code
  "+268": (number) => /^[0-9]{8}$/.test(number), // Swaziland (Eswatini): 8 digits after country code
  "+963": (number) => /^[0-9]{8,9}$/.test(number), // Syria: 8-9 digits after country code
  "+886": (number) => /^[0-9]{9}$/.test(number), // Taiwan: 9 digits after country code
  "+992": (number) => /^[0-9]{9}$/.test(number), // Tajikistan: 9 digits after country code
  "+255": (number) => /^[0-9]{9}$/.test(number), // Tanzania: 9 digits after country code
  "+670": (number) => /^[0-9]{7}$/.test(number), // Timor-Leste: 7 digits after country code
  "+228": (number) => /^[0-9]{8}$/.test(number), // Togo: 8 digits after country code
  "+690": (number) => /^[0-9]{4}$/.test(number), // Tokelau: 4 digits after country code
  "+676": (number) => /^[0-9]{5,7}$/.test(number), // Tonga: 5-7 digits after country code
  "+216": (number) => /^[0-9]{8}$/.test(number), // Tunisia: 8 digits after country code
  "+993": (number) => /^[0-9]{8}$/.test(number), // Turkmenistan: 8 digits after country code
  "+688": (number) => /^[0-9]{5,6}$/.test(number), // Tuvalu: 5-6 digits after country code
  "+598": (number) => /^[0-9]{8}$/.test(number), // Uruguay: 8 digits after country code
  "+998": (number) => /^[0-9]{9}$/.test(number), // Uzbekistan: 9 digits after country code
  "+678": (number) => /^[0-9]{5,7}$/.test(number), // Vanuatu: 5-7 digits after country code
  "+58": (number) => /^[0-9]{10}$/.test(number), // Venezuela: 10 digits after country code
  "+84": (number) => /^[0-9]{9,10}$/.test(number), // Vietnam: 9-10 digits after country code
  "+681": (number) => /^[0-9]{6}$/.test(number), // Wallis and Futuna: 6 digits after country code
  "+967": (number) => /^[0-9]{7,9}$/.test(number), // Yemen: 7-9 digits after country code
  "+260": (number) => /^[0-9]{9}$/.test(number), // Zambia: 9 digits after country code
  "+263": (number) => /^[0-9]{9}$/.test(number), // Zimbabwe: 9 digits after country code
};
